// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package gopb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// pb_json resp with google/protobuf/any.proto
type PbJson struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Secret               string   `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Data                 *any.Any `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbJson) Reset()         { *m = PbJson{} }
func (m *PbJson) String() string { return proto.CompactTextString(m) }
func (*PbJson) ProtoMessage()    {}
func (*PbJson) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *PbJson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbJson.Unmarshal(m, b)
}
func (m *PbJson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbJson.Marshal(b, m, deterministic)
}
func (m *PbJson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbJson.Merge(m, src)
}
func (m *PbJson) XXX_Size() int {
	return xxx_messageInfo_PbJson.Size(m)
}
func (m *PbJson) XXX_DiscardUnknown() {
	xxx_messageInfo_PbJson.DiscardUnknown(m)
}

var xxx_messageInfo_PbJson proto.InternalMessageInfo

func (m *PbJson) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PbJson) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PbJson) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *PbJson) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PbJson)(nil), "gopb.pb_json")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0x48, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0xcf, 0x2f, 0x48, 0x92, 0x92, 0x4c, 0xcf, 0xcf, 0x4f,
	0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x25, 0x95, 0xa6, 0xe9, 0x27, 0xe6, 0x55, 0x42, 0x14, 0x28, 0x55,
	0x72, 0xb1, 0x17, 0x24, 0xc5, 0x67, 0x15, 0xe7, 0xe7, 0x09, 0x09, 0x71, 0xb1, 0x24, 0xe7, 0xa7,
	0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9,
	0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x90, 0x18,
	0x17, 0x5b, 0x71, 0x6a, 0x72, 0x51, 0x6a, 0x89, 0x04, 0x33, 0x58, 0x02, 0xca, 0x13, 0xd2, 0xe0,
	0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x51, 0x60, 0xd4, 0xe0, 0x36, 0x12, 0xd1, 0x83, 0x58,
	0xad, 0x07, 0xb3, 0x5a, 0xcf, 0x31, 0xaf, 0x32, 0x08, 0xac, 0xc2, 0x89, 0x2d, 0x0a, 0xec, 0xba,
	0x24, 0x36, 0xb0, 0x9c, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x55, 0x78, 0x80, 0x7b, 0xb6, 0x00,
	0x00, 0x00,
}
