goredis:
  endpoint: "127.0.0.1:6379"
  password: ""
  db: 0
  pool_size: 0
  min_idle_conns: 0
  max_conn_age: "0s"
  dial_timeout: "0s"
  read_timeout: "0s"
  write_timeout: "0s"
  pool_timeout: "0s"
  idle_timeout: "0s"
  idle_check_frequency: "0s"
  max_retries: 0
  min_retry_backoff: "0s"
  max_retry_backoff: "0s"
